# Generated by Django 3.1.1 on 2021-03-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zastava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=255)),
                ('first', models.CharField(max_length=255)),
                ('second', models.CharField(max_length=255)),
                ('third', models.CharField(max_length=255)),
            ],
        ),
    ]
