# Generated by Django 3.1.1 on 2021-03-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bojanka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zastava',
            name='ime',
            field=models.CharField(default='', max_length=255),
        ),
    ]
